# Generated by Django 4.2.6 on 2023-10-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(max_length=200, null=True, upload_to='students/images/'),
        ),
    ]
