# Generated by Django 4.2.6 on 2023-10-14 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_alter_track_description_alter_track_image'),
        ('students', '0005_student_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='tracks.track'),
        ),
    ]
