# Generated by Django 4.2.6 on 2023-10-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='image',
            field=models.ImageField(null=True, upload_to='tracks/images/'),
        ),
    ]
