# Generated by Django 4.2.6 on 2023-10-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_track_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tracks/images/'),
        ),
    ]
